### ISSUE TITLE
Add instructions on how to install for collaboration

### ISSUE THREAD

**Issue by pedrocruzio** [ChrisMichaelPerezSantiago/covid19-gql#1]
What are the steps to run the server?

**Comment by chrismichaelps** [comment]
## ⚙️ Basic collaboration installation process
More configuration could be added in the future, but for now with those processes it would be enough to start the project.

**Installation of all dependencies**

```shell
npm install
```

**Start local server**
Local server port assigned to **PORT 3000**

```shell
npm run start
```

**GraphQL Playground**

```shell
http://localhost:3000/graphql
```
